@echo off
echo Compiling Io Folder...
"C:/Program Files\Java\jdk1.7.0_09/bin/javac.exe" -d bin -sourcepath src src\com\alex\io/*.java
echo Done Compiling Io Folder...
echo Compiling Loaders Folder...
"C:/Program Files\Java\jdk1.7.0_09/bin/javac.exe" -d bin -sourcepath src src\com\alex\loaders\clientscripts/*.java
"C:/Program Files\Java\jdk1.7.0_09/bin/javac.exe" -d bin -sourcepath src src\com\alex\loaders\images/*.java
"C:/Program Files\Java\jdk1.7.0_09/bin/javac.exe" -d bin -sourcepath src src\com\alex\loaders\interfaces/*.java
"C:/Program Files\Java\jdk1.7.0_09/bin/javac.exe" -d bin -sourcepath src src\com\alex\loaders\items/*.java
echo Done Compiling Loaders Folder...
echo Compiling Store Folder...
"C:/Program Files\Java\jdk1.7.0_09/bin/javac.exe" -d bin -sourcepath src src\com\alex\store/*.java
echo Done Compiling Store Folder...
echo Compiling Tools Folder...
"C:/Program Files\Java\jdk1.7.0_09/bin/javac.exe" -d bin -sourcepath src src\com\alex\tools\clientCacheUpdater/*.java
"C:/Program Files\Java\jdk1.7.0_09/bin/javac.exe" -d bin -sourcepath src src\com\alex\tools\itemsDefsEditor/*.java
echo Done Compiling Tools Folder...
echo Compiling Util Folder...
"C:/Program Files\Java\jdk1.7.0_09/bin/javac.exe" -d bin -sourcepath src src\com\alex\util/bzip2/*.java
"C:/Program Files\Java\jdk1.7.0_09/bin/javac.exe" -d bin -sourcepath src src\com\alex\util/crc32/*.java
"C:/Program Files\Java\jdk1.7.0_09/bin/javac.exe" -d bin -sourcepath src src\com\alex\util/gzip/*.java
"C:/Program Files\Java\jdk1.7.0_09/bin/javac.exe" -d bin -sourcepath src src\com\alex\util/whirlpool/*.java
echo Done Compiling Util Folder...
echo Compiling Utils Folder...
"C:/Program Files\Java\jdk1.7.0_09/bin/javac.exe" -d bin -sourcepath src src\com\alex\utils/*.java
echo Done Compiling Utils Folder...
echo Compiling Apache Folders...
"C:/Program Files\Java\jdk1.7.0_09/bin/javac.exe" -d bin -sourcepath src src\org\apache\tools\bzip2/*.java
echo Compiled all folders!
pause